### ISSUE TITLE
要不要增加一个定位元素宽高已知和未知的区分？

### ISSUE THREAD

**Issue by toBeTheLight** [yanhaijing/vertical-center#2]
比如这样：

# 水平垂直居中

## 仅居中元素宽高已知适用
- [absolute + 负margin](http://yanhaijing.com/vertical-center/absolute1.html)
- [absolute + margin auto](http://yanhaijing.com/vertical-center/absolute2.html)
- [absolute + calc](http://yanhaijing.com/vertical-center/absolute3.html)

## 居中元素宽高未知适用
- [absolute + transform](http://yanhaijing.com/vertical-center/absolute4.html)
- [lineheight](http://yanhaijing.com/vertical-center/lineheight.html)
- [table](http://yanhaijing.com/vertical-center/table.html)
- [css-table](http://yanhaijing.com/vertical-center/css-table.html)
- [writing-mode](http://yanhaijing.com/vertical-center/writing-mode.html)
- [flex](http://yanhaijing.com/vertical-center/flex.html)
- [grid](http://yanhaijing.com/vertical-center/grid.html)

不过不加宽高的话`writing-mode`和`table`的样式要做一些修改。

**Comment by yanhaijing** [comment]
6666，求提个pr
